server {
    listen 80;
    listen [::]:80;

    charset utf-8;

    client_max_body_size 20M;

    root /usr/share/nginx/html;

    location / {
        try_files $uri$args $uri$args/ /index.html;
    }

    location /grafana {
        proxy_pass http://grafana:3000;
    }

    location /api {
        proxy_pass http://backend:8080/api;
    }

    location /swagger-ui {
        proxy_pass http://backend:8080/swagger-ui;
    }

    location /v3 {
        proxy_pass http://backend:8080/v3;
    }

    location /be/static {
        proxy_pass http://backend:8080/static;
    }
}